window.adnI18n && window.adnI18n.add({
  /* attribute values (placeholder / aria-label / title) */
  "Deschide meniul": "Open menu",
  "Închide meniul": "Close menu",
  "Meniu": "Menu",
  "Schimbă limba": "Change language",
  "Schimbă tema": "Change theme",
  "Panou de administrare": "Admin panel",
  "Logo partener": "Partner logo",
  "Fotografie echipă / birou": "Team / office photo",

  /* topbar + header + drawer */
  "Broker autorizat de leasing și credite · birouri în București, Galați, Sibiu, Prahova, Bistrița-Năsăud, Mureș și Neamț": "Authorised leasing and credit broker · offices in Bucharest, Galați, Sibiu, Prahova, Bistrița-Năsăud, Mureș and Neamț",
  "Acasă": "Home",
  "Companie": "Company",
  "Tipuri de leasing": "Leasing types",
  "Simulatoare": "Simulators",
  "Simulatoare și cereri": "Simulators & requests",
  "Toate tipurile, comparate": "All types, compared",
  "Toate tipurile, structuri comparate": "All types, structures compared",
  "Despre echipa noastră": "About our team",
  "Parte a ADN Finanz": "Part of ADN Finanz",
  "Parte a ADN FINANZ": "Part of ADN Finanz",
  "Cum lucrăm": "How we work",
  "Condiții de finanțare": "Financing conditions",
  "Vorbește cu un consultant": "Talk to a consultant",
  "Nu știi ce ți se potrivește?": "Not sure what fits you?",
  "Rata ta, în 10 secunde": "Your instalment, in 10 seconds",
  "Configurezi dosarul în patru pași și cererea pleacă deja completată.": "Configure your file in four steps and the request goes out already filled in.",
  "Deschide simulatorul →": "Open the simulator →",
  "Verifică eligibilitatea →": "Check eligibility →",
  "Cinci întrebări și îți spunem ce structură are cele mai mari șanse de aprobare.": "Five questions, and we'll tell you which structure has the best approval odds.",
  "Sună acum": "Call now",
  "Sună": "Call",
  "Ofertă în 2 minute": "Quote in 2 minutes",
  "Îți răspundem în aceeași zi lucrătoare. Birouri în București și în șapte județe.": "We reply the same business day. Offices in Bucharest and seven counties.",
  "Ești eligibil? Află în 5 întrebări": "Are you eligible? Find out in 5 questions",
  "Verdict pe loc, cu avansul și dobânda estimate pentru profilul tău. Fără interogare în birourile de credit.": "Instant verdict, with the estimated down payment and interest rate for your profile. No credit-bureau inquiry.",
  "Începe verificarea →": "Start the check →",
  "Cerere pe WhatsApp": "WhatsApp request",
  "Cerere rapidă pe WhatsApp": "Quick WhatsApp request",
  "Mesaj precompletat cu simularea": "Message pre-filled with your simulation",
  "Firmele de leasing cu care lucrăm": "The leasing companies we work with",
  "Răspuns în aceeași zi lucrătoare": "Reply the same business day",
  "Brokeri autorizați, cu vechime": "Authorised, experienced brokers",
  "Brokeri de credite autorizați, cu vechime": "Authorised, experienced credit brokers",
  "Firme, start-up-uri, persoane fizice": "Companies, start-ups, individuals",
  "Temă întunecată": "Dark theme",
  "Intermediere gratuită": "Free brokerage",
  "Răspuns în 24-48h": "Response within 24-48h",
  "Fără obligații": "No obligations",

  /* drawer badges */
  "NOI": "US",
  "AUT": "CAR",
  "ECH": "EQP",
  "IMO": "RE",

  /* homepage hero */
  "Broker de leasing pentru firme, PFA și persoane fizice": "Leasing broker for companies, sole traders and individuals",
  "Un dosar, ofertele mai multor firme de leasing": "One file, offers from several leasing companies",
  "Configurezi finanțarea mai jos în patru pași, vezi șapte structuri comparate pe aceleași date și trimiți cererea deja completată. Noi negociem condițiile cu partenerii; serviciul de intermediere este gratuit.": "Configure your financing below in four steps, see seven structures compared on the same data and send a request that's already filled in. We negotiate the terms with our partners; the brokerage service is free.",
  "Auto, flotă, echipamente, imobiliar.": "Cars, fleet, equipment, real estate.",
  "O singură echipă acoperă toate tipurile de leasing.": "One team covers every type of leasing.",
  "Vezi verdictul înainte de a aplica": "See the verdict before you apply",
  "— scor de eligibilitate, avans recomandat, șanse de aprobare.": "— eligibility score, recommended down payment, approval odds.",
  "Cererea se completează singură": "The request fills itself in",
  "din ce ai configurat. Adaugi doar numele și telefonul.": "from what you configured. You only add your name and phone number.",
  "Configurează dosarul": "Configure your file",
  "Ce primești în 48 de ore": "What you get within 48 hours",
  "Structurile partenerilor care acceptă profilul tău": "The structures our partners offer for your profile",
  "Structurile partenerilor care acceptă tipul tău de echipament": "The structures our partners offer for your type of equipment",
  "Rata, comisioanele și costul total, explicate": "The instalment, fees and total cost, explained",
  "Rata, comisionul de analiză și costul total, explicate": "The instalment, assessment fee and total cost, explained",
  "Lista exactă de documente pentru dosarul tău": "The exact document list for your file",
  "Analiza preliminară este gratuită și nu se raportează în birourile de credit.": "The preliminary review is free and isn't reported to credit bureaus.",
  "Începe simularea": "Start the simulation",

  /* leasing types grid */
  "Tipuri": "Types",
  "Ce tipuri de leasing intermediem": "The leasing types we broker",
  "Fiecare tip are propriile condiții, parteneri și calculator. Alege direcția care se potrivește cu ce vrei să finanțezi.": "Each type has its own conditions, partners and calculator. Pick the direction that matches what you want to finance.",
  "Automobile": "Cars",
  "Autoturisme noi și rulate": "New and used cars",
  "Autoturisme noi și rulate, firmă sau persoană fizică": "New and used cars, for companies or individuals",
  "Vezi condițiile →": "See the conditions →",
  "Operațional": "Operating",
  "Operațional sau financiar": "Operating or finance",
  "Flotă cu servicii incluse": "Fleet with services included",
  "Asigurări, mentenanță și anvelope în rată, fără grija revânzării.": "Insurance, maintenance and tyres included in the instalment, no resale worries.",
  "Vezi cum funcționează →": "See how it works →",
  "Echipamente": "Equipment",
  "Utilaje, medical, IT": "Machinery, medical, IT",
  "Utilaje, medical, IT, construcții": "Machinery, medical, IT, construction",
  "De la utilaje agricole și linii de producție la aparatură medicală și servere.": "From farm machinery and production lines to medical equipment and servers.",
  "Vezi soluțiile →": "See the solutions →",
  "Imobiliar": "Real estate",
  "Sedii, hale, spații comerciale": "Offices, warehouses, commercial spaces",
  "Alternativa la creditul ipotecar comercial, cu perioade de până la 12 ani.": "An alternative to commercial mortgage loans, with terms of up to 12 years.",
  "Vezi detaliile →": "See the details →",
  "Financiar": "Finance",
  "Devii proprietar la final": "You own it at the end",
  "Structura clasică: avans, rate și valoare reziduală mică la finalul contractului.": "The classic structure: down payment, instalments and a small residual value at the end of the contract.",
  "Simulează rata →": "Run the simulation →",
  "Nu știi care": "Not sure which",
  "Verificare de eligibilitate": "Eligibility check",
  "Verificare eligibilitate": "Eligibility check",
  "Cinci întrebări și îți spunem ce structură are cele mai mari șanse de aprobare.": "Five questions, and we'll tell you which structure has the best approval odds.",

  /* conditions */
  "Condiții": "Conditions",
  "Condiții leasing auto": "Car leasing conditions",
  "Firmele de leasing auto partenere solicită, în principiu, următoarele condiții. Totuși, pentru o ofertă personalizată nu ezitați să ne contactați.": "Our partner car-leasing companies generally ask for the following conditions. For a personalised quote, feel free to contact us.",
  "Firme cu istoric": "Companies with a track record",
  "Firme cu peste un an de activitate, cu rezultate financiare bune": "Companies trading for over a year, with good financial results",
  "Avansul se stabilește în funcție de analiza financiară.": "The down payment is set based on the financial review.",
  "Ofertă personalizată": "Personalised quote",
  "Firme nou înființate": "Newly formed companies",
  "Firme nou înființate (mai puțin de un an de la înființare)": "Newly formed companies (less than a year since incorporation)",
  "Persoane fizice": "Individuals",

  /* process */
  "Proces": "Process",
  "Cum lucrăm și de ce serviciul este gratuit": "How we work, and why the service is free",
  "Compari": "Compare",
  "Ne spui ce vrei să finanțezi, iar noi trimitem aceleași date la firmele de leasing partenere.": "Tell us what you want to finance, and we send the same data to our partner leasing companies.",
  "Ești asistat": "You're assisted",
  "Un consultant dedicat îți explică diferențele dintre oferte și răspunde la întrebări pe tot parcursul.": "A dedicated consultant explains the differences between the offers and answers questions the whole way through.",
  "Aplici": "You apply",
  "Pregătim dosarul împreună, îl depunem și urmărim aprobarea până la semnare.": "We prepare the file together, submit it and follow the approval through to signing.",
  "Gratuit": "Free",
  "De ce nu plătești nimic": "Why you pay nothing",
  "Brokerajul este remunerat de firmele de leasing, nu de client. Serviciile noastre de intermediere sunt gratuite.": "The brokerage fee is paid by the leasing companies, not the client. Our brokerage services are free.",

  /* benefits */
  "Beneficii": "Benefits",
  "Ce se schimbă când mergi prin broker": "What changes when you go through a broker",
  "Nu alergi între finanțatori": "You don't run between lenders",
  "Ai o singură discuție cu noi. Ofertele vin comparate, pe aceleași date, ca diferențele să fie evidente.": "You have a single conversation with us. The offers come compared, on the same data, so the differences are obvious.",
  "Condiții negociate": "Negotiated terms",
  "Volumul intermediat de echipa ADN Finanz ne dă spațiu de negociere pe dobândă, avans și perioadă.": "The volume brokered by the ADN Finanz team gives us room to negotiate on interest, down payment and term.",
  "Consultant dedicat": "A dedicated consultant",
  "Aceeași persoană îți duce dosarul de la prima simulare până la semnarea contractului.": "The same person carries your file from the first simulation through to signing the contract.",
  "Costuri explicate": "Costs explained",
  "Dobândă, comisioane, asigurări și valoare reziduală, puse pe masă înainte de decizie.": "Interest, fees, insurance and residual value, laid out before you decide.",

  /* team */
  "Echipa": "Team",
  "Despre echipa noastră": "About our team",
  "Consultanții noștri financiari sunt brokeri de credite cu vechime, autorizați, a căror punct de vedere referitor la alegerea unei oferte de leasing este bazat pe expertiză.": "Our financial consultants are experienced, authorised credit brokers whose take on choosing a leasing offer is grounded in expertise.",
  "Experiență în finanțări": "Experience in financing",
  "Cunoștințe auto": "Automotive know-how",
  "Serviciile noastre de intermediere leasing auto sunt gratuite": "Our car-leasing brokerage services are free",
  "Programează o discuție": "Book a conversation",

  /* ADN Finanz group */
  "Grup": "Group",
  "Proiectul": "The project",
  "Despre ADN Finanz": "About ADN Finanz",
  "Birouri în București și în județele Galați, Sibiu, Prahova, Bistrița-Năsăud, Mureș și Neamț.": "Offices in Bucharest and the counties of Galați, Sibiu, Prahova, Bistrița-Năsăud, Mureș and Neamț.",

  /* coverage / tools */
  "Acoperire": "Coverage",
  "Tot ce poți face cu ADN Leasing": "Everything you can do with ADN Leasing",
  "Finanțări, unelte de calcul și serviciile care țin dosarul în mișcare, într-un singur loc.": "Financing, calculators and the services that keep your file moving, all in one place.",
  "Finanțări": "Financing",
  "Leasing automobile": "Car leasing",
  "Leasing operațional": "Operating leasing",
  "Leasing echipamente": "Equipment leasing",
  "Leasing imobiliar": "Real-estate leasing",
  "Leasing financiar": "Finance leasing",
  "Unelte": "Tools",
  "Simulator de rate": "Instalment simulator",
  "Comparator de oferte": "Offer comparator",
  "Condiții pe profil de client": "Conditions by client profile",
  "Servicii incluse": "Services included",
  "Negocierea dobânzii cu partenerii": "Negotiating interest with partners",
  "Pregătirea și depunerea dosarului": "Preparing and submitting the file",
  "Consultanță în achiziția bunului": "Advice on purchasing the asset",
  "Asistență până la semnare și livrare": "Support through to signing and delivery",
  "Fără cost pentru client": "No cost to the client",

  /* contact */
  "Solicită o ofertă personalizată sau informații generale": "Request a personalised quote or general information",
  "Îți răspundem în aceeași zi lucrătoare. Dacă preferi, scrie-ne direct pe WhatsApp sau sună-ne.": "We reply the same business day. If you prefer, message us directly on WhatsApp or call us.",
  "Telefon": "Phone",
  "Scrie-ne un mesaj": "Send us a message",
  "Program": "Hours",
  "Mulțumim,": "Thank you,",
  "Am primit solicitarea. Un consultant te contactează în aceeași zi lucrătoare cu ofertele partenerilor.": "We've received your request. A consultant will contact you the same business day with our partners' offers.",
  "Trimite altă solicitare": "Send another request",
  "Numele tău": "Your name",
  "Adresa ta de email": "Your email address",
  "Mesajul tău (opțional)": "Your message (optional)",
  "Dacă vrei cifre concrete, configurează dosarul în simulatorul din partea de sus a paginii — cererea de acolo pleacă deja completată.": "If you want concrete figures, configure your file in the simulator at the top of the page — the request from there goes out already filled in.",
  "Trimite solicitarea": "Send the request",
  "Scrie-ne pe WhatsApp": "Message us on WhatsApp",
  "Calculele afișate sunt orientative și nu constituie o ofertă ferm.": "The figures shown are indicative and do not constitute a firm offer.",

  /* eligibility page */
  "Vezi în cinci pași ce finanțare ți se potrivește": "See in five steps which financing fits you",
  "Răspunzi la câteva întrebări despre tine și despre bunul dorit. La final primești o evaluare orientativă și structura de leasing cu cele mai mari șanse de aprobare.": "Answer a few questions about yourself and the asset you want. At the end you'll get an indicative assessment and the leasing structure with the best approval odds.",
  "Cine solicită finanțarea?": "Who is requesting the financing?",
  "Continuă": "Continue",
  "Vezi rezultatul": "See the result",
  "Înapoi": "Back",
  "Reia verificarea": "Restart the check",
  "Șanse bune": "Good odds",
  "Șanse bune de aprobare": "Good approval odds",
  "Profilul tău se încadrează în condițiile uzuale ale partenerilor. Cu documentele complete, primul răspuns vine în 24-48 de ore.": "Your profile fits our partners' usual criteria. With complete documents, the first response comes within 24-48 hours.",
  "Aprobare probabilă, cu ajustări": "Likely approval, with adjustments",
  "Se poate finanța, dar avansul sau perioada vor fi ajustate. Îți arătăm variantele partenerilor care acceptă acest profil.": "It can be financed, but the down payment or term will be adjusted. We'll show you the options from partners who accept this profile.",
  "Dosarul are nevoie de analiză": "The file needs a closer look",
  "Există elemente care cer o discuție înainte de aplicare: restanțe active, activitate scurtă sau avans insuficient. Un consultant poate propune o structură alternativă, cu avans mai mare sau garanții suplimentare.": "There are points that call for a conversation before applying: active arrears, a short trading history or an insufficient down payment. A consultant can suggest an alternative structure, with a larger down payment or extra guarantees.",
  "Trimite dosarul unui consultant": "Send the file to a consultant",

  /* eligibility questions */
  "Firmă cu istoric": "Established company",
  "Firmă cu peste un an de activitate": "Company trading for over a year",
  "Firmă nou înființată": "Newly formed company",
  "PFA / profesie liberală": "Sole trader / freelance profession",
  "PFA sau profesie liberală": "Sole trader or freelance profession",
  "cabinet, birou": "practice, office",
  "cabinet, birou individual": "practice, individual office",
  "Persoană fizică": "Individual",
  "inclusiv venituri din străinătate": "including income from abroad",
  "Ce vrei să finanțezi?": "What do you want to finance?",
  "Autoturism sau vehicul comercial": "Car or commercial vehicle",
  "Echipamente sau utilaje": "Equipment or machinery",
  "agro, industrial, medical, IT": "agri, industrial, medical, IT",
  "Imobil comercial": "Commercial property",
  "sediu, hală, spațiu comercial": "office, warehouse, commercial space",
  "Bunul este nou sau rulat?": "Is the asset new or used?",
  "Nou, de la dealer sau producător": "New, from a dealer or manufacturer",
  "de la dealer sau producător": "from a dealer or manufacturer",
  "Rulat": "Used",
  "nou sau rulat": "new or used",
  "Ce avans poți susține?": "What down payment can you cover?",
  "De regulă zero": "Usually zero",
  "posibil la operațional": "possible with operating leasing",
  "Cum arată istoricul de plată?": "What does your payment history look like?",
  "Fără restanțe și fără întârzieri": "No arrears and no delays",
  "istoric curat": "clean history",
  "Întârzieri mici, închise": "Minor delays, since resolved",
  "sub 30 de zile": "under 30 days",
  "Restanțe active": "Active arrears",
  "necesită analiză": "needs a review",

  /* eligibility recommendations */
  "Leasing financiar auto": "Car finance leasing",
  "Nou știi care": "Not sure which",
  "avans mai mare": "higher down payment",
  "avans minim": "minimum down payment",
  "avans uzual": "usual down payment",
  "avans, în majoritatea cazurilor": "down payment, in most cases",
  "cea mai bună rată din": "the best instalment out of",
  "cele mai bune condiții": "the best conditions",
  "condiții mai bune": "better conditions",
  "condiții uzuale": "usual conditions",
  "confortabil": "comfortable",
  "de regulă mică": "usually small",
  "dobândă anuală de la": "annual interest from",
  "dobândă puțin mai mare": "slightly higher interest",
  "durata contractului": "the contract term",
  "este garanția principală": "is the main collateral",
  "finanțabil la unii parteneri": "financeable with some partners",
  "hală, birou, spațiu comercial": "warehouse, office, commercial space",
  "incluse în rată": "included in the instalment",
  "inclusiv din străinătate": "including from abroad",
  "istoric curat": "clean history",
  "județe cu birouri ADN Finanz": "counties with ADN Finanz offices",
  "la finalul contractului, la valoarea reziduală stabilită de la început.": "at the end of the contract, at the residual value set from the start.",
  "leasing operațional, servicii incluse": "operating leasing, services included",
  "minimul uzual": "the usual minimum",
  "necesită analiză": "needs a review",
  "operațional": "operating leasing",
  "pe an": "a year",
  "perioadă de finanțare": "financing term",
  "perioadă de plată": "repayment term",
  "permisă în majoritatea contractelor; verificăm comisionul înainte de semnare.": "allowed in most contracts; we check the fee before signing.",
  "poate fi finanțat": "can be financed",
  "primul răspuns la dosar": "first response on the file",
  "rată de la · dobândă": "instalment from · interest",
  "risc de revânzare": "resale risk",
  "sediu, hală, spațiu comercial": "office, warehouse, commercial space",
  "structuri pentru dosarul tău": "structures for your file",
  "structuri, la": "structures, from",
  "transfer de proprietate": "transfer of ownership",
  "utilaje, medical, IT, construcții": "machinery, medical, IT, construction",
  "variabil, la semnare": "variable, at signing",
  "venituri salariale sau din străinătate": "salary income or income from abroad",
  "· șanse": "· odds",
  "anul începerii activității": "the year we started",

  /* partners page */
  "Parteneri": "Partners",
  "O singură discuție, ofertele mai multor finanțatori": "One conversation, offers from several lenders",
  "Lucrăm cu firme de leasing și divizii de leasing ale băncilor. Tu discuți cu un consultant ADN Leasing, iar noi trimitem dosarul acolo unde profilul tău are cele mai mari șanse și cele mai bune condiții.": "We work with leasing companies and the leasing divisions of banks. You talk to one ADN Leasing consultant, and we route your file wherever your profile has the best odds and the best terms.",
  "Firme de leasing partenere": "Partner leasing companies",
  "Logourile partenerilor se încarcă în locurile marcate. Lista finală se actualizează în funcție de acordurile în vigoare.": "Partner logos load into the marked spots. The final list is updated according to the agreements in force.",
  "Avantaj": "Advantage",
  "Ce câștigi când mergem la mai mulți finanțatori": "What you gain when we approach several lenders",
  "Condiții comparate, nu presupuse": "Compared conditions, not assumed",
  "Aceleași date trimise la mai mulți parteneri produc diferențe reale de dobândă, avans și comisioane. Le vezi una lângă alta, înainte de a semna.": "The same data sent to several partners produces real differences in interest, down payment and fees. You see them side by side, before you sign.",
  "Dosarul merge unde are șanse": "The file goes where it has a chance",
  "Fiecare finanțator are politici proprii pe vechimea firmei, tipul bunului sau vârsta vehiculului. Alegem partenerii potriviți profilului tău, nu îi contactăm la nimereală.": "Each lender has its own policies on company age, asset type or vehicle age. We pick the partners that fit your profile, not at random.",
  "Un singur interlocutor": "A single point of contact",
  "Consultantul care îți preia dosarul îl duce până la final: documente, clarificări, aprobare, semnare. Nu ești pasat de la un departament la altul.": "The consultant who takes on your file carries it through to the end: documents, clarifications, approval, signing. You're not passed from one department to another.",
  "Serviciu gratuit pentru client": "Free for the client",
  "Nu percepem comision de la client; brokerajul este remunerat de firmele de leasing. Interesul nostru este ca dosarul să fie aprobat în condiții pe care le poți susține.": "We don't charge the client a fee; the brokerage is paid by the leasing companies. Our interest is that your file gets approved on terms you can actually sustain.",
  "Cum ajunge dosarul tău la finanțatori": "How your file reaches lenders",
  "Profil și obiectiv": "Profile and goal",
  "Stabilim ce bun finanțezi, ce avans poți susține și pe ce perioadă vrei rata. Verificarea de eligibilitate din site este primul filtru.": "We establish what asset you're financing, what down payment you can cover and over what term you want the instalment. The site's eligibility check is the first filter.",
  "Selecția partenerilor": "Selecting the partners",
  "Alegem finanțatorii care acceptă profilul tău și trimitem dosarul cu aceleași date, ca ofertele să fie comparabile.": "We choose the lenders that accept your profile and submit the file with the same data, so the offers are comparable.",
  "Negociere și decizie": "Negotiation and decision",
  "Negociem dobânda și comisioanele, îți explicăm diferențele dintre oferte și decizi tu, cu costul total în față.": "We negotiate the interest and fees, explain the differences between the offers, and you decide, with the total cost laid out.",
  "Contractare": "Contracting",
  "Pregătim documentele finale, urmărim semnarea și rămânem punctul tău de contact și după livrarea bunului.": "We prepare the final documents, follow through on signing and remain your point of contact even after the asset is delivered.",
  "Ești firmă de leasing sau furnizor?": "Are you a leasing company or a supplier?",
  "Dacă vrei să primești dosare de la echipa ADN Leasing sau să oferi finanțare clienților tăi, scrie-ne și stabilim cadrul de colaborare.": "If you'd like to receive files from the ADN Leasing team or offer financing to your clients, get in touch and we'll set up a collaboration framework.",
  "Propune o colaborare": "Propose a partnership",

  /* car leasing page */
  "Leasing auto pentru firme și persoane fizice": "Car leasing for companies and individuals",
  "Autoturisme noi de la dealer sau auto rulate din piață. Configurezi dosarul mai jos, iar noi trimitem dosarul la firmele de leasing partenere și îți întoarcem variantele care trec de analiza financiară.": "New cars from a dealer or used cars from the market. Configure your file below, and we send it to our partner leasing companies and bring back the options that pass their financial review.",
  "Nou sau rulat, firmă ori persoană fizică": "New or used, for companies or individuals",
  "Pe firmă sau pe persoană fizică, de la dealer sau din piața second-hand.": "For companies or individuals, from a dealer or the second-hand market.",
  "Cere ofertă": "Request a quote",
  "Vreau 3 oferte pentru mașina mea": "I want 3 offers for my car",
  "Primești 3 oferte pentru mașina dorită": "Get 3 offers for the car you want",
  "Ce mașină vrei? Marcă, model, an": "Which car do you want? Make, model, year",
  "Ce ne întreabă clienții": "What our clients ask us",
  "Pot lua în leasing o mașină cumpărată de la persoană fizică?": "Can I lease a car bought from an individual?",
  "Da, în multe cazuri se poate, cu condiția ca vehiculul să respecte limitele de vechime și kilometraj ale finanțatorului. Spune-ne ce mașină ai găsit și verificăm care partener o acceptă.": "Yes, in many cases you can, provided the vehicle meets the lender's age and mileage limits. Tell us which car you found and we'll check which partner accepts it.",
  "Cât durează de la cerere până la aprobare?": "How long does it take from request to approval?",
  "Primul răspuns vine în 24-48 de ore de la dosarul complet. Termenul final depinde de finanțator și de documentele firmei sau ale persoanei fizice.": "The first response comes within 24-48 hours of a complete file. The final timeline depends on the lender and on the company's or individual's documents.",
  "Ce documente trebuie pregătite?": "What documents do I need to prepare?",
  "Pentru firme: documentele societății și ultimele situații financiare. Pentru persoane fizice: act de identitate și documente de venit, inclusiv pentru veniturile din străinătate.": "For companies: the company's documents and latest financial statements. For individuals: an ID document and proof of income, including income earned abroad.",
  "Cât costă serviciul de intermediere?": "How much does the brokerage service cost?",
  "Nimic. Serviciile noastre de intermediere sunt gratuite pentru client; suntem remunerați de firmele de leasing partenere.": "Nothing. Our brokerage services are free for the client; we're paid by our partner leasing companies.",

  /* equipment leasing page */
  "Utilajul intră în producție, capitalul rămâne în firmă": "The equipment goes into production, the capital stays in the company",
  "Leasing pentru utilaje și echipamente": "Leasing for machinery and equipment",
  "Utilaje agricole, linii de producție, echipamente medicale, IT sau construcții. Bunul finanțat este garanția principală, așa că dosarul se mișcă mai repede decât la un credit clasic.": "Farm machinery, production lines, medical, IT or construction equipment. The financed asset is the main collateral, so the file moves faster than with a classic loan.",
  "Utilaje, medical, IT, construcții": "Machinery, medical, IT, construction",
  "Garanția este echipamentul.": "The collateral is the equipment itself.",
  "De regulă nu blochezi alte active ale firmei.": "You usually don't tie up any other company assets.",
  "Grafic corelat cu încasările": "Schedule matched to your cash flow",
  "— sezonier în agricultură, unde partenerul permite.": "— seasonal in agriculture, where the partner allows it.",
  "Achiziții interne și intracomunitare": "Domestic and intra-EU purchases",
  "TVA finanțabil la unii parteneri": "VAT financeable with some partners",
  "Vreau ofertă pentru echipament": "I want a quote for equipment",
  "Primești ofertele pentru echipamentul tău": "Get the offers for your equipment",
  "Ce echipament și de la ce furnizor": "What equipment, and from which supplier",
  "Se finanțează echipamente cumpărate din afara României?": "Can you finance equipment bought from outside Romania?",
  "Da, achizițiile intracomunitare sunt uzuale. Contează furnizorul, documentele de import și modul în care se face plata către acesta.": "Yes, intra-EU purchases are common. What matters is the supplier, the import documents and how the payment to them is made.",
  "Pot finanța un utilaj de la o firmă din același grup?": "Can I finance equipment from a company in the same group?",
  "Tranzacțiile între părți afiliate sunt privite cu atenție și cer, de regulă, un raport de evaluare independent. Se poate, dar dosarul are un pas suplimentar.": "Transactions between affiliated parties are looked at carefully and usually require an independent valuation report. It's possible, but the file has an extra step.",
  "Firma mea are un an de activitate. Este posibil?": "My company has been trading for a year. Is that possible?",
  "Da, cu avans mai mare și, uneori, cu garanții suplimentare. Îți spunem din prima discuție ce structură are șanse reale de aprobare.": "Yes, with a larger down payment and, sometimes, extra guarantees. We'll tell you from the first conversation which structure has real approval odds.",
  "Cât durează aprobarea?": "How long does approval take?",
  "Primul răspuns vine în 24-48 de ore de la dosarul complet; pentru echipamente mai complexe, evaluarea tehnică poate adăuga câteva zile.": "The first response comes within 24-48 hours of a complete file; for more complex equipment, the technical assessment may add a few days.",

  /* real estate leasing page */
  "Sediul devine al firmei, fără credit ipotecar": "The premises become the company's own, without a mortgage loan",
  "Leasing imobiliar pentru firme": "Real-estate leasing for companies",
  "Finanțatorul cumpără imobilul, tu îl folosești din prima zi și devii proprietar la finalul contractului. Perioade mai lungi și garanții mai simple decât la un credit ipotecar comercial.": "The lender buys the property, you use it from day one and you become the owner at the end of the contract. Longer terms and simpler collateral than a commercial mortgage loan.",
  "Sedii, hale și spații comerciale": "Offices, warehouses and commercial spaces",
  "Imobilul este garanția.": "The property itself is the collateral.",
  "Constituirea garanției e mai simplă decât la bancă.": "Setting up the collateral is simpler than at a bank.",
  "Perioade de 5 până la 12 ani": "Terms from 5 to 12 years",
  "TVA-ul poate fi finanțat": "VAT can be financed",
  ", ceea ce reduce efortul inițial de cash.": ", which reduces the initial cash outlay.",
  "Trimite-ne detaliile proprietății și datele firmei; îți spunem ce avans și ce perioadă sunt realiste.": "Send us the property details and your company's information; we'll tell you what down payment and term are realistic.",
  "Ai găsit imobilul? Verificăm finanțarea": "Found the property? Let's check the financing",
  "Avansul și perioada realiste pentru imobilul tău": "The realistic down payment and term for your property",
  "Ce imobile intră în discuție": "What kind of properties are eligible",
  "Sedii, hale, spații comerciale": "Offices, warehouses, commercial spaces",
  "Sediul firmei, spații de birouri, clădiri mixte cu destinație comercială.": "Company premises, office space, mixed-use buildings with a commercial purpose.",
  "Spații industriale": "Industrial spaces",
  "Hale de producție și depozitare, platforme logistice, terenuri aferente activității.": "Production and storage warehouses, logistics platforms, land related to the business.",
  "Spații comerciale": "Retail spaces",
  "Unități la stradă, spații în centre comerciale, clinici, unități HoReCa.": "Street-front units, shopping-centre spaces, clinics, hospitality (HoReCa) units.",
  "Cine este proprietarul pe durata contractului?": "Who owns the property during the contract?",
  "Finanțatorul. Firma ta folosește imobilul în baza contractului de leasing și devine proprietar la final, după plata valorii reziduale.": "The lender. Your company uses the property under the leasing contract and becomes the owner at the end, after paying the residual value.",
  "Se poate finanța și un imobil în construcție?": "Can a property still under construction be financed?",
  "De regulă se finanțează imobile finalizate și recepționate. Pentru proiecte în curs, discutăm soluții etapizate cu partenerii care le acceptă.": "Usually, only completed and handed-over properties are financed. For ongoing projects, we discuss staged solutions with the partners who accept them.",
  "Ce se întâmplă cu TVA-ul?": "What happens with VAT?",
  "În multe structuri TVA-ul poate fi finanțat, ceea ce reduce efortul inițial de cash. Modul exact se stabilește împreună cu finanțatorul și contabilul firmei.": "In many structures VAT can be financed, which reduces the initial cash outlay. The exact approach is set together with the lender and the company's accountant.",
  "Este mai rapid decât un credit ipotecar comercial?": "Is it faster than a commercial mortgage loan?",
  "În general da, pentru că bunul finanțat este garanția, iar procesul de constituire a garanției este mai simplu. Termenul rămâne dependent de evaluare și de documentația imobilului.": "Generally yes, because the financed asset is itself the collateral, and setting up that collateral is simpler. The timeline still depends on the valuation and the property's paperwork.",

  /* operational leasing page */
  "Flota merge, administrarea o preia altcineva": "The fleet runs, someone else handles the admin",
  "Leasing operațional pentru flote": "Operating leasing for fleets",
  "Închiriere pe termen lung cu asigurări, mentenanță, anvelope și vehicul de înlocuire în rată. Plătești utilizarea, nu proprietatea, iar la final predai sau schimbi vehiculele.": "Long-term rental with insurance, maintenance, tyres and a replacement vehicle included in the instalment. You pay for use, not ownership, and at the end you hand back or swap the vehicles.",
  "Flotă cu asigurări și mentenanță incluse": "Fleet with insurance and maintenance included",
  "Un cost lunar previzibil.": "A predictable monthly cost.",
  "Service-ul, RCA, CASCO și anvelopele intră în aceeași rată.": "Servicing, third-party and comprehensive insurance, and tyres are all part of the same instalment.",
  "Zero risc de revânzare.": "Zero resale risk.",
  "Predai sau schimbi vehiculul": "You hand back or swap the vehicle",
  "la finalul contractului.": "at the end of the contract.",
  "Spune-ne câte vehicule și cât rulează": "Tell us how many vehicles and how much they run",
  "Construim pachetul cu partenerii care acoperă profilul flotei tale și îți arătăm rata cu servicii incluse.": "We build the package with the partners that match your fleet's profile and show you the instalment with services included.",
  "Vreau o ofertă de flotă": "I want a fleet quote",
  "Primești oferta de flotă, cu servicii incluse": "Get your fleet quote, services included",
  "Câte vehicule și ce rulaj anual": "How many vehicles and what annual mileage",
  "Ce include": "What's included",
  "Asigurare RCA și CASCO": "Third-party and comprehensive insurance",
  "Mentenanță și revizii programate": "Maintenance and scheduled servicing",
  "Anvelope de sezon și depozitare": "Seasonal tyres and storage",
  "Vehicul de înlocuire pe durata reparațiilor": "A replacement vehicle during repairs",
  "Asistență rutieră și taxe anuale": "Roadside assistance and annual duties",
  "Rămâne la tine": "Stays with you",
  "Combustibilul și consumabilele zilnice": "Fuel and day-to-day consumables",
  "Amenzile și taxele de drum din utilizare": "Fines and road-usage charges from driving",
  "Daunele care nu intră în uzura normală": "Damage beyond normal wear and tear",
  "Ce mișcă cel mai mult rata": "What moves the instalment the most",
  "Pachetul se construiește pe utilizarea reală a flotei. Kilometrajul estimat și durata contractului sunt cele două variabile care mișcă cel mai mult rata.": "The package is built around your fleet's actual usage. Estimated mileage and contract length are the two variables that move the instalment the most.",
  "De la câte vehicule se justifică leasingul operațional?": "From how many vehicles does operating leasing make sense?",
  "Se poate face și pentru un singur vehicul, dar avantajul administrativ se simte cel mai clar de la trei-patru vehicule în sus, când mentenanța și asigurările încep să consume timp intern.": "It can work for even a single vehicle, but the administrative benefit is clearest from three or four vehicles upward, once maintenance and insurance start eating into internal time.",
  "Ce se întâmplă dacă depășesc kilometrajul contractat?": "What happens if I go over the contracted mileage?",
  "Se aplică un tarif pe kilometrul suplimentar, stabilit în contract. Dacă rulajul real diferă mult de estimare, contractul se poate renegocia în timp.": "An extra-kilometre rate applies, set out in the contract. If actual mileage differs a lot from the estimate, the contract can be renegotiated over time.",
  "Rata este deductibilă integral?": "Is the instalment fully deductible?",
  "La firmă, rata de leasing operațional este tratată ca cheltuială de exploatare. Regimul exact al deductibilității îl confirmă contabilul tău, în funcție de utilizarea vehiculului.": "For a company, the operating-lease instalment is treated as an operating expense. The exact deductibility rules are confirmed by your accountant, depending on how the vehicle is used.",
  "Pot cumpăra vehiculul la final?": "Can I buy the vehicle at the end?",
  "În unele contracte există opțiunea de achiziție la valoarea de piață. O verificăm de la început, dacă intenția ta este să păstrezi vehiculul.": "Some contracts include a purchase option at market value. We check this from the start if your intention is to keep the vehicle.",
  "Vezi leasingul financiar": "See finance leasing",
  "Nu ești sigur? Întreabă un consultant": "Not sure? Ask a consultant",
  "Comparație operațional vs. financiar pe flota ta": "Operating vs. finance leasing comparison for your fleet",

  /* finance leasing page */
  "Plătești în rate, la final bunul este al tău": "You pay in instalments, and the asset is yours at the end",
  "Leasing financiar, structura clasică": "Finance leasing, the classic structure",
  "Avans, rate lunare și valoare reziduală mică la final, după care proprietatea trece la tine. Se aplică pentru autoturisme, vehicule comerciale și echipamente.": "A down payment, monthly instalments and a small residual value at the end, after which ownership passes to you. It applies to cars, commercial vehicles and equipment.",
  "Devii proprietar": "You become the owner",
  "la finalul contractului, la valoarea reziduală stabilită de la început.": "at the end of the contract, at the residual value set from the start.",
  "Dobândă fixă sau variabilă": "Fixed or variable interest",
  "— îți arătăm ce înseamnă fiecare în cost total, nu doar în rată.": "— we show you what each one means in total cost, not just in the instalment.",
  "Rambursare anticipată": "Early repayment",
  "permisă în majoritatea contractelor; verificăm comisionul înainte de semnare.": "allowed in most contracts; we check the fee before signing.",
  "Compară ofertele": "Compare offers",
  "Vreau ofertă pentru imobil": "I want a quote for a property",
  "Trimite-ne oferta furnizorului": "Send us the supplier's quote",
  "Oferta furnizorului sau factura proformă": "The supplier's quote or pro-forma invoice",
  "Pot plăti anticipat contractul?": "Can I repay the contract early?",
  "Da. Majoritatea contractelor permit rambursarea anticipată, parțială sau integrală, cu un comision prevăzut în contract. Îl verificăm înainte de semnare.": "Yes. Most contracts allow early repayment, partial or full, with a fee set out in the contract. We check it before signing.",
  "Dobânda este fixă sau variabilă?": "Is the interest fixed or variable?",
  "Există ambele variante. Cea fixă îți dă predictibilitate, cea variabilă pornește de obicei mai jos, dar se recalculează periodic în funcție de indicele de referință.": "Both options exist. The fixed rate gives you predictability; the variable one usually starts lower but is periodically recalculated based on the reference index.",
  "Ce se întâmplă la finalul contractului?": "What happens at the end of the contract?",
  "Plătești valoarea reziduală, iar bunul trece în proprietatea ta. Documentele de transfer se pregătesc de finanțator.": "You pay the residual value, and the asset becomes your property. The transfer documents are prepared by the lender.",
  "Persoană fizică sau firmă, ce e mai avantajos?": "Individual or company, which is more advantageous?",
  "Depinde de utilizare și de regimul fiscal. Pe firmă intervin deductibilitatea și TVA-ul; pe persoană fizică, procesul este mai simplu. Facem comparația concret, pe cazul tău.": "It depends on the use and the tax treatment. For a company, deductibility and VAT come into play; for an individual, the process is simpler. We run the comparison concretely, on your case.",

  /* simulator: steps & shared UI */
  "Cifrele": "The figures",
  "Ofertele": "The offers",
  "Cererea": "The request",
  "Bunul": "The asset",
  "Profilul": "The profile",
  "Pasul": "Step",
  "din": "of",
  "Continuă": "Continue",
  "Vezi detalii": "See details",
  "Vezi rezultatul": "See the result",
  "Solicită varianta recomandată": "Request the recommended option",
  "Solicită oferta": "Request the quote",
  "Cere ofertă": "Request a quote",
  "Scurtează perioada": "Shorten the term",
  "Sortează": "Sort",
  "Cost total": "Total cost",
  "Cost total minim": "Lowest total cost",
  "Cea mai mică rată": "Lowest instalment",
  "Structura recomandată": "Recommended structure",
  "Șanse de aprobare": "Approval odds",
  "Rezultat orientativ": "Indicative result",
  "Rezultatul din dreapta se recalculează la fiecare modificare.": "The result on the right recalculates with every change.",
  "Consultantul primește exact datele din acest panou, fără să le mai completezi tu.": "The consultant receives exactly the data from this panel, without you having to fill it in again.",
  "Poți sări direct la oferte oricând; datele lipsă le completăm în discuție.": "You can jump straight to the offers any time; we'll fill in any missing data during the conversation.",
  "Dosarul tău, în timp real": "Your file, in real time",

  /* simulator: asset step */
  "Ce vrei să finanțezi?": "What do you want to finance?",
  "Alegerea schimbă partenerii, dobânda de start și perioadele disponibile.": "Your choice changes the partners, the starting interest rate and the available terms.",
  "Autoturism": "Car",
  "Autoturism · cifrele finanțării": "Car · financing figures",
  "nou sau rulat, firmă ori persoană fizică": "new or used, for companies or individuals",
  "Flotă auto": "Car fleet",
  "Flotă auto · cifrele finanțării": "Car fleet · financing figures",
  "Echipamente · cifrele finanțării": "Equipment · financing figures",
  "utilaje, medical, IT, construcții": "machinery, medical, IT, construction",
  "Imobil comercial": "Commercial property",
  "Imobil comercial · cifrele finanțării": "Commercial property · financing figures",
  "sediu, hală, spațiu comercial": "office, warehouse, commercial space",
  "Bunul este nou sau rulat?": "Is the asset new or used?",
  "Nou": "New",
  "de la dealer sau producător": "from a dealer or manufacturer",
  "Rulat": "Used",
  "dobândă puțin mai mare": "slightly higher interest",

  /* simulator: profile step */
  "Firmă cu istoric": "Established company",
  "peste 12 luni de activitate": "trading for over 12 months",
  "Firmă nou înființată": "Newly formed company",
  "sub 12 luni": "under 12 months",
  "PFA / profesie liberală": "Sole trader / freelance profession",
  "cabinet, birou individual": "practice, individual office",
  "Persoană fizică": "Individual",
  "inclusiv venituri din străinătate": "including income from abroad",
  "Fără întârzieri": "No delays",
  "istoric curat": "clean history",
  "Întârzieri mici, închise": "Minor delays, since resolved",
  "sub 30 de zile": "under 30 days",
  "Restanțe active": "Active arrears",
  "necesită analiză": "needs a review",

  /* simulator: numbers step */
  "Moneda": "Currency",
  "Preț fără TVA": "Price excl. VAT",
  "Valoare echipament fără TVA": "Equipment value excl. VAT",
  "Valoare imobil fără TVA": "Property value excl. VAT",
  "Valoare vehicul fără TVA": "Vehicle value excl. VAT",
  "Avans estimat": "Estimated down payment",
  "Avans ·": "Down payment ·",
  "Perioadă": "Term",
  "Ești deja în zona optimă de avans pentru profilul ales. O perioadă mai scurtă reduce costul total al finanțării.": "You're already in the optimal down-payment range for the chosen profile. A shorter term reduces the total cost of financing.",

  /* simulator: offers step */
  "Criteriu": "Criterion",
  "Rată": "Instalment",
  "Dobândă": "Interest",
  "Dobândă estimată": "Estimated interest",
  "Dobândă fixă": "Fixed interest rate",
  "Dobândă variabilă": "Variable interest rate",
  "Rată constantă, fără recalculări.": "A constant instalment, with no recalculations.",
  "Se recalculează trimestrial, după IRCC.": "Recalculated quarterly, based on the IRCC reference index.",
  "Cu valoare reziduală": "With a residual value",
  "Reziduală 20% plătită la final.": "A 20% residual value paid at the end.",
  "Grafic flexibil": "Flexible schedule",
  "Graficul se ajustează o dată pe an.": "The schedule is adjusted once a year.",
  "Flote și utilizare intensă": "Fleets and intensive use",
  "Asigurări și mentenanță incluse în rată.": "Insurance and maintenance included in the instalment.",
  "Comision de analiză": "Assessment fee",
  "Fără comision de analiză": "No assessment fee",
  "Cash minim la semnare": "Minimum cash at signing",
  "Zero costuri inițiale, dobândă mai mare.": "Zero upfront costs, higher interest.",
  "Aprobare rapidă": "Fast approval",
  "Termen scurt de livrare": "Short delivery time",
  "Analiză prioritară, documentație redusă.": "Priority review, reduced paperwork.",
  "Valoare reziduală": "Residual value",
  "Predictibilitate pe toată durata": "Predictability for the whole term",
  "Toleranță la variații de indice": "Tolerant of index swings",
  "Rată lunară minimă": "Lowest monthly instalment",
  "Încasări sezoniere": "Seasonal cash flow",

  /* simulator: request/done steps */
  "Cererea ta, deja completată": "Your request, already filled in",
  "Am preluat tot ce ai configurat. Adaugă doar numele și telefonul, iar consultantul primește dosarul exact așa cum îl vezi mai jos.": "We've captured everything you configured. Just add your name and phone number, and the consultant receives the file exactly as you see it below.",
  "Dosar": "File",
  "Modifică varianta sau datele": "Change the option or the details",
  "Trimite dosarul către parteneri": "Send the file to our partners",
  "Analiza preliminară este gratuită și nu se raportează în birourile de credit. Poți renunța oricând.": "The preliminary review is free and isn't reported to credit bureaus. You can stop at any time.",
  "Numele tău": "Your name",
  "Telefon": "Phone",
  "Email (opțional, pentru oferta scrisă)": "Email (optional, for the written offer)",
  "Detalii despre bun (opțional)": "Details about the asset (optional)",

  /* header/footer misc */
  "Sună 0732 961 237": "Call 0732 961 237",
  "Trimite pe WhatsApp": "Send via WhatsApp",
});

/* text generated at runtime by the simulator / eligibility quiz (amounts, terms,
   scores) — exact strings can't be enumerated, so these are pattern-translated. */
window.adnI18n && window.adnI18n.addPatterns([
  { re: /^Pasul (\d+) din (\d+)$/, build: function (m) { return "Step " + m[1] + " of " + m[2]; } },
  { re: /^(\d+) \/ (\d+) puncte$/, build: function (m) { return m[1] + " / " + m[2] + " points"; } },
  { re: /^Minim acceptat pentru profilul ales: (\d+)%$/, build: function (m) { return "Minimum accepted for the chosen profile: " + m[1] + "%"; } },
  { re: /^(\d+) luni \((\d+) (an|ani)\)$/, build: function (m) { return m[1] + " months (" + m[2] + (m[3] === "an" ? " year)" : " years)"); } },
  { re: /^(\d+) luni$/, build: function (m) { return m[1] + " months"; } },
  { re: /^Aplică avans (\d+)%$/, build: function (m) { return "Apply " + m[1] + "% down payment"; } },
  { re: /^Cu un avans de (\d+)% rata scade cu aproximativ ([\d.,]+) (€|lei) pe lună și crește șansa de aprobare\.$/, build: function (m) { return "With a " + m[1] + "% down payment the instalment drops by about " + m[2] + " " + m[3] + " a month and improves your approval odds."; } },
  { re: /^(.+) · (nou|rulat)$/, build: function (m) { return window.adnI18n.lookup(m[1]) + " · " + (m[2] === "nou" ? "new" : "used"); } },
  { re: /^(.+) · ([\d.,]+) (€|lei)\/lună$/, build: function (m) { return window.adnI18n.lookup(m[1]) + " · " + m[2] + " " + m[3] + "/month"; } },
  { re: /^([\d.,]+) (€|lei)\/lună$/, build: function (m) { return m[1] + " " + m[2] + "/month"; } },
]);

/* second pass — gaps found while QA-testing every page/step with a real browser */
window.adnI18n && window.adnI18n.add({
  "Cereri, dobânzi și configurare simulator": "Requests, interest rates and simulator settings",
  "Vezi diferențele într-un singur loc": "See the differences in one place",
  "Răspunzi la 5 întrebări și îți spunem ce structură are cele mai mari șanse de aprobare.": "Answer 5 questions and we'll tell you which structure has the best approval odds.",
  "Rată, avans și cost total pe 1-5 ani": "Instalment, down payment and total cost over 1-5 years",
  "Utilaje și aparatură, nou sau rulat": "Machinery and equipment, new or used",
  "Estimare operațional": "Operating leasing estimate",
  "Rată lunară cu servicii incluse": "Monthly instalment with services included",
  "Rata lunară cu pachetul de servicii inclus": "The monthly instalment with the service package included",
  "Avans, dobândă și valoare reziduală": "Down payment, interest and residual value",
  "Brokeraj de credite și leasing din 2012": "Credit and leasing brokerage since 2012",
  "Trei pași și de ce serviciul e gratuit": "Three steps, and why the service is free",
  "Firme, start-up-uri și persoane fizice": "Companies, start-ups and individuals",
  "Servicii incluse, de regulă fără avans": "Services included, usually no down payment",
  "Rată, avans și cost total": "Instalment, down payment and total cost",
  "intermediat în 2024": "brokered in 2024",
  "/ lună": "/ month",
  "Avans": "Down payment",
  "Sumă finanțată": "Amount financed",
  "Perioadă rate": "Instalment term",
  "Vechime maximă auto": "Maximum car age",
  "3 ani la începutul contractului": "3 years old at the start of the contract",
  "5 ani la începutul contractului": "5 years old at the start of the contract",
  "3 ani și 50.000 km": "3 years and 50,000 km",
  "5 ani și 180.000 km": "5 years and 180,000 km",
  "Se acceptă venituri și din străinătate.": "Income from abroad is accepted too.",
  "înglobează activități de brokeraj de credite și de leasing + consultanță în achiziții auto. Activitatea a început în 2012, iar rezultatele și echipa au crescut exponențial în timp. În 2024 valoarea intermediată a bunurilor finanțate de echipa noastră prin leasing sau credit a depășit 20 milioane Euro.": "brings together credit and leasing brokerage + car-purchase consultancy. The business started in 2012, and both results and team have grown exponentially since. In 2024, the value of goods financed by our team through leasing or credit exceeded €20 million.",
  "Brokeraj de leasing și credite, parte a ADN FINANZ. Comparăm ofertele firmelor de leasing partenere, iar serviciile noastre de intermediere sunt gratuite.": "Leasing and credit brokerage, part of ADN FINANZ. We compare offers from our partner leasing companies, and our brokerage services are free.",
  ", cu TVA finanțabil la unii parteneri.": ", with VAT financeable with some partners.",
  ", cu rată corelată cu chiria pe care nu o mai plătești.": ", with an instalment matched to the rent you no longer pay.",
  "Analiza pornește de la capacitatea de plată a firmei și de la actele imobilului.": "The review starts from the company's ability to pay and the property's paperwork.",
  "Analiza preliminară": "Preliminary review",
  "Aparatură medicală și stomatologică, echipamente de laborator, servere, infrastructură IT, HoReCa.": "Medical and dental equipment, lab equipment, servers, IT infrastructure, hospitality (HoReCa).",
  "Aprobare și contractare": "Approval and contracting",
  "Avans de la 15%": "Down payment from 15%",
  "Avansul: fiecare 5% suplimentar scade sensibil rata lunară": "Down payment: every extra 5% noticeably lowers the monthly instalment",
  "Birouri și sedii": "Offices and premises",
  "Ce avans poți susține?": "What down payment can you cover?",
  "Ce echipamente finanțăm": "What equipment we finance",
  "Ce intră în rata lunară": "What's included in the monthly instalment",
  "Ce pregătim pentru dosar": "What we prepare for the file",
  "Ce schimbă rata": "What changes the instalment",
  "Compari rata, comisionul și costul total înainte să semnezi.": "Compare the instalment, the fee and the total cost before you sign.",
  "Comparăm ofertele partenerilor": "We compare our partners' offers",
  "Comparăm ofertele partenerilor și îți trimitem variantele reale": "We compare our partners' offers and send you the real options",
  "Comparăm structurile partenerilor pe aceleași date și îți arătăm unde diferența se face din dobândă și unde din comisioane.": "We compare our partners' structures on the same data and show you where the difference comes from interest and where from fees.",
  "Condițiile de mai jos sunt cele uzuale. Pentru o ofertă personalizată, analiza financiară poate schimba avansul sau perioada.": "The conditions below are the usual ones. For a personalised quote, the financial review may change the down payment or the term.",
  "Construcții și industrie": "Construction and industry",
  "Costul total, nu doar rata lunară": "The total cost, not just the monthly instalment",
  "De regulă fără avans": "Usually no down payment",
  "Depășirea kilometrajului contractat": "Exceeding the contracted mileage",
  "Dobândă anuală": "Annual interest",
  "Documente, clarificări, aprobare. Tu alegi mașina și semnezi.": "Documents, clarifications, approval. You choose the car and sign.",
  "Documentele firmei și ultimele situații financiare": "The company's documents and latest financial statements",
  "Documentele societății și certificatul constatator": "The company's documents and certificate of good standing",
  "Dosarul îl facem noi.": "We put the file together.",
  "Evaluare și due diligence": "Valuation and due diligence",
  "Evaluarea este orientativă și nu reprezintă o decizie de finanțare. Aprobarea finală aparține firmei de leasing, după analiza documentelor.": "The assessment is indicative and doesn't represent a financing decision. Final approval belongs to the leasing company, after reviewing the documents.",
  "Excavatoare, încărcătoare, linii de producție, mașini-unelte, ambalare și logistică internă.": "Excavators, loaders, production lines, machine tools, packaging and internal logistics.",
  "Fiecare tip de bun are parteneri și condiții proprii.": "Each asset type has its own partners and conditions.",
  "Flotă auto cu servicii incluse": "Car fleet with services included",
  "Fără avans": "No down payment",
  "Fără cost și fără interogare în birourile de credit la etapa de analiză preliminară.": "No cost and no credit-bureau inquiry at the preliminary review stage.",
  "Fără restanțe și fără întârzieri": "No arrears and no delays",
  "Interogăm firmele de leasing cu care lucrăm, negociem dobânda și îți punem pe masă variantele care trec de analiza financiară.": "We query the leasing companies we work with, negotiate the interest rate and put on the table the options that pass the financial review.",
  "La finalul contractului, imobilul trece în proprietatea firmei, la valoarea reziduală stabilită inițial.": "At the end of the contract, the property transfers to the company, at the residual value set at the start.",
  "Lista finală depinde de finanțator. Îți trimitem un checklist exact după prima discuție.": "The final list depends on the lender. We'll send you an exact checklist after the first conversation.",
  "Medical, IT și servicii": "Medical, IT and services",
  "Ne spui ce mașină vrei, ce avans poți susține și pe ce perioadă. Simularea din pagină e punctul de plecare al discuției.": "Tell us which car you want, what down payment you can cover and over what term. The simulation on this page is the starting point of the conversation.",
  "Oferta furnizorului sau anunțul bunului dorit": "The supplier's quote or the listing for the asset you want",
  "Pașii de evaluare și due diligence": "The valuation and due-diligence steps",
  "Pe baza ei comparăm structurile de finanțare și îți arătăm ce avans și ce dobândă sunt realiste pentru firma ta.": "Based on it, we compare financing structures and show you what down payment and interest rate are realistic for your company.",
  "Pentru achiziții intracomunitare verificăm și modul de plată către furnizor.": "For intra-EU purchases we also check how payment to the supplier is made.",
  "Pentru bunuri rulate: raport de evaluare, unde e cerut": "For used assets: a valuation report, where required",
  "Perioada: mai lungă înseamnă rată mai mică, dar cost total mai mare": "Term: longer means a smaller instalment, but a higher total cost",
  "Potrivit pentru": "Suited for",
  "Pregătim dosarul și semnezi": "We prepare the file and you sign",
  "Profilul determină avansul minim acceptat și documentele din dosar.": "The profile determines the minimum accepted down payment and the documents in the file.",
  "Profilul tău intră în condițiile uzuale ale partenerilor. Cu documentele complete, primul răspuns vine în 24-48 de ore.": "Your profile fits our partners' usual criteria. With complete documents, the first response comes within 24-48 hours.",
  "Raport de evaluare, situația juridică a imobilului, urbanism și acte de proprietate. Aici se decide valoarea finanțabilă.": "Valuation report, the property's legal status, zoning and ownership documents. This is where the financeable value gets decided.",
  "Restanțele active sunt principalul motiv de refuz.": "Active arrears are the main reason for refusal.",
  "Restanțele active sunt principalul motiv de refuz. Spune-ne din start, ca să nu pierzi timp.": "Active arrears are the main reason for refusal. Tell us upfront, so you don't waste time.",
  "Semnarea contractului de leasing, achiziția imobilului de către finanțator și predarea în folosință.": "Signing the leasing contract, the lender's purchase of the property and handover for use.",
  "Simulează rata": "Run the simulation",
  "Simulezi și trimiți datele": "You simulate and send your details",
  "Situația creditelor și a leasingurilor în derulare": "The status of ongoing loans and leases",
  "Structura TVA și valoarea reziduală propusă": "The VAT structure and the proposed residual value",
  "Structurile reflectă practica uzuală a partenerilor. Dobânda, comisioanele și valoarea reziduală se confirmă după analiza documentelor; calculul nu constituie o ofertă ferm.": "The structures reflect our partners' usual practice. Interest, fees and residual value are confirmed after reviewing the documents; the calculation is not a firm offer.",
  "Structură": "Structure",
  "Tipul bunului: nou sau rulat, cu impact pe dobândă": "Asset condition: new or used, which affects the interest rate",
  "Tractoare, combine, utilaje de sol și irigații. Grafic de plată corelat cu sezonul, unde partenerul permite.": "Tractors, combines, ground-working and irrigation equipment. Payment schedule matched to the season, where the partner allows it.",
  "Trei structuri de finanțare comparate pe aceleași date": "Three financing structures compared on the same data",
  "Trimite-ne simularea și primești varianta ta": "Send us your simulation and get your option",
  "Ultimele situații financiare și balanța recentă": "The latest financial statements and a recent trial balance",
  "Un avans mai mare crește șansele de aprobare și scade rata.": "A larger down payment increases approval odds and lowers the instalment.",
  "Un consultant îți pregătește documentele, urmărește aprobarea și te ține la curent până la livrarea mașinii.": "A consultant prepares your documents, follows the approval and keeps you posted through to the car's delivery.",
  "Un consultant îți răspunde în aceeași zi lucrătoare cu ofertele care trec de analiza financiară.": "A consultant replies the same business day with the offers that pass the financial review.",
  "Valoarea reziduală rămâne problema finanțatorului, nu a ta.": "The residual value is the lender's risk, not yours.",
  "Variantele cu dobândă fixă și variabilă, comparate": "The fixed- and variable-rate options, compared",
  "Vechimea influențează dobânda și avansul cerut.": "Age affects the interest rate and the required down payment.",
  "Verificarea dacă TVA-ul poate fi finanțat": "Checking whether VAT can be financed",
  "Verificăm capacitatea de plată a firmei și tipul imobilului, apoi identificăm partenerii care finanțează acest gen de tranzacție.": "We check the company's ability to pay and the type of property, then identify the partners who finance this kind of transaction.",
  "avans mai mare": "higher down payment",
  "hală, birou, spațiu comercial": "warehouse, office, commercial space",
  "Întrebări": "Questions",
  "Îți arătăm unde diferența se face din dobândă și unde din comisioane.": "We show you where the difference comes from interest and where from fees.",
  "și cu rată tratată drept cheltuială de exploatare la firmă.": "and with the instalment treated as an operating expense for the company.",
  "și dobândă de la 4,55% pe an, negociată de noi, nu afișată de un singur finanțator.": "and interest from 4.55% a year, negotiated by us, not simply quoted by a single lender.",
});
